apiVersion: v1
kind: Secret
metadata: 
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==

#mongo-user $echo -n mongouser | base64
#mongo-password $echo -n mongopassword | base64